# Project information
site_name: Grin++ Documentation
site_url: https://grinplusplus.github.io/docs
site_author: Paouky
site_description: 'Grin++ Documentation'

# Repository
repo_name: GrinPlusPlus
repo_url: https://github.com/GrinPlusPlus/GrinPlusPlus
# edit_uri: https://github.com/GrinPlusPlus/documentation

# Copyright
# copyright: Copyright &copy; 2018 - 2021 Grin Developers

theme:
  palette:
    scheme: slate
  name: material
  logo: assets/images/512x512_logo.png
  favicon: assets/images/512x512_logo.png
  language: en
# features:
#   - tabs

# Plugins
# plugins:
#  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GrinPlusPlus
    - icon: fontawesome/brands/telegram
      link: https://t.me/GrinPP

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.superfences
  - meta
  - toc:
      permalink: ⚓︎
      toc_depth: 0 # Disables TOC



nav:
- Home: "index.md"
- Setup Wallet: "setup.md"
- Receive: "receive.md"
- Send: "send.md"
- Balance: "balance.md"
- Settings: "settings.md"
- Advanced:
    - 🛠 Build: "build.md"
    - 📄 API: "api.md"
